secrets:
  env:
    file: .env.production
services:
  dev:
    container_name: tasks-server
    hostname: tasks-server
    restart: unless-stopped
    secrets:
      - env
    tty: true
    build:
      args:
        - PORT=${PORT}
        - TAR=${TAR}
      context: .
      secrets:
        - env
      no_cache: true
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    volumes:
      - db:/home/nonroot/app/.database
    networks:
      - net
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 64M
volumes:
  db:
networks:
  net: