services:
  dev:
    container_name: tasks-server
    hostname: tasks-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      args:
        - PORT=${PORT}
      context: .
      no_cache: true
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - db:/home/app/db
    networks:
      - net
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 64M
    oom_score_adj: 200
volumes:
  db:
networks:
  net: