version: "3.8"
secrets:
  env:
    file: .env.production
services:
  app:
    container_name: tasks-server
    hostname: tasks-server
    restart: unless-stopped
    secrets:
      - env
    build:
      args:
        - PORT=${PORT}
      context: .
      secrets:
        - env
      no_cache: true
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - db:/app/db
    networks:
      - net
    env_file:
      - .env.production
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 64M
volumes:
  db:
networks:
  net: